version: '3.8'


services:
  janganmales-agent:
    container_name: janganmales-agent
    build: .
    ports:
      - "8080:8080"
    env_file: 
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
